### PR TITLE
I painted (some) bees

### PR DESCRIPTION
**Pull request by Gcat101**
Bees from "resourceful bees" will now appear coloured on the minimap.

### CODE REVIEW

**Review by TemperedFool — COMMENTED** [review]
Do these work with the FTB Chunks map or with Journeymap? I assume the improvement here is having bee-specific faces, which is cool.

Is the Beeper face distinct from what a creeper looks like?

**Comment by Gcat101** [comment]
1) Both 
2) Yes, beeper looks like this:
creeper_bee

**Comment by TemperedFool** [comment]
Yeah, I saw that - what does the actual creeper one look like? Mostly interested in how the two look on a map together, can you tell them apart?

**Comment by Gcat101** [comment]
beeper/creeper on map
creeper_bee 
Снимок экрана 2021-08-28 в 17 32 18

**Review by TemperedFool — APPROVED** [review]
Looks great to me then!

**Comment by NillerMedDild** [comment]
Thanks for the PR!

The changed files are shown as a ton of old files with reduced file size, I think you may need to re-do this PR?
Additionally, please target the Develop branch :)

**Comment by Gcat101** [comment]
I just copied the faces of the bees from resourceful bees' assets and resized them.

**Comment by Darkere** [comment]
The Files already existed, they just all had the same texture.

**Comment by TemperedFool** [comment]
Yeah, I had done a quick-and-dirty bee face based off the vanilla bee; my art skills are not such that I was going to customize it per bee!

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Ah I see, sorry about that :D

**Pull request merged**
