### PR TITLE
TerraForged changes attempt #1

### PR DESCRIPTION
**Pull request by theboo**
Removed some horizontal spread and added a bit of verticality to some of the mountainous terrain features, also lowered sea level a bit which seems to allow for surface caves and ravines to appear!!!

if anyone has time to test this that would be great! lmk if u have any feedback

### CODE REVIEW

**Comment by theboo** [comment]
looks like we have control over the slime islands through TF, def will need to lower their frequency a bit xD

**Comment by NillerMedDild** [comment]
I spawned next to a cave opening, gg :P

**Comment by NillerMedDild** [comment]
Several even! 

Could we remove BYG's Autumnal Valley? I think the "pumpkin trees" are an abomination :P

I found ~15 slime islands in 2 minutes flying in creative, you're right, slightly too many xD

**Comment by theboo** [comment]
Woohoo! Yeah, I never touched sea level before but when I was going through settings I saw it's defaulted to 63 which is a block higher than vanilla, I lowered it to 56 since many flat areas are still well above sea level seems to have allowed the caves to pop through

**Comment by theboo** [comment]
Yeh easy mode, imma go through the biome weights again later this week... There's a pvj biome that looks horrendous (overgrown spires) in TF that I think needs yeeted as well..

**Comment by NillerMedDild** [comment]
PVJ has no biomes though :P nor do we have a biome called overgrown spires

**Comment by pm065** [comment]
> PVJ has no biomes though :P nor do we have a biome called overgrown spires

It does now (it's in the process of being returned to the state it was in in 1.15)

**Comment by NillerMedDild** [comment]
No? Unless they were added without a trace in commits and changelogs.

**Comment by theboo** [comment]
There's 2 pvj biomes in the pool, idr the other ones name tho but do /terra locate biome project and they will show up

**Comment by theboo** [comment]
One of em looks nice the other is just surface ore everywhere lol TF might flatten the spires depending on how they added them

**Comment by pm065** [comment]
Verdant Sands is the other one I think

**Comment by theboo** [comment]
Ahh yeah it's lush style desert... We might have that covered with atmospheric tho so it might need yeeted too

**Comment by pm065** [comment]
See changelog here: https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys/files/3275473
Isn't Atmospheric gonna get oofed in 5.0?

**Comment by theboo** [comment]
Neither are in the biome weights conf yet, it may be a WIP thing similar to byg canyons which are disabled by default in byg but TF picks them up anyway so have to manually change weight to 0

**Comment by NillerMedDild** [comment]
Ahh I see, my bad - It is a bit meh in TF, agreed.
billede

> See changelog here: https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys/files/3275473

Oh derp, I thought they were odd names for groundcover :P

**Pull request merged**
