### PR TITLE
Eidolon: clarify the need to find a witch and not a swamp in the first quest

### PR DESCRIPTION
**Pull request by Larandar**
I spent a few hours looking for a swamp and throwing a book in water (granted I was tired) before reading the book and facepalmed so hard I finally got some sleep 🤦 

Please people like me need to be helped 👍

### CODE REVIEW

**Comment by NillerMedDild** [comment]
To be honest I think it's clear enough - Find a magic user in a swamp, sounds like a witch to me :P

**Comment by Larandar** [comment]
With terraforged swamps are not that common (the nearest for me was 13k block aways from spawn and was a few chunks only), the quest is IMO misleading since you don't need a swamp but only a witch.

**Comment by NillerMedDild** [comment]
Hmm :/ I know it says visit a swamp, but it's just to solidy which kind of magic user you need to find. I guess we can change it.

**Comment by NillerMedDild** [comment]
I'd like 

> "Try paying a visit to your local witch, giving her your exemplar of Ars Ecclesia, and if you ask nicely, you might learn something new..."

to be changed to 

> "Try paying a visit to your local witch and toss her your Ars Ecclesia, you might learn something new..."

**Comment by Larandar** [comment]
Done 👍

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by Merlo17** [comment]
FYI I initially left it vague on purpose, since the mod itself doesn't want to tell you straight up where the book should be thrown, and I feel like giving away the answer like that would spoil the fun for players who are legitimately interested in solving the little puzzle themselves (the ones who aren't will probably google the answer just as quickly)

I can see the swamp line being misleading and it should probably be changed, but maybe we can come up with something a bit more creative that doesn't ruin the process straight up?

**Comment by NillerMedDild** [comment]
Yeah that'd be nice, I couldn't think of anything though :/

**Comment by TemperedFool** [comment]
Something about "Double, double toil and trouble"?

**Comment by Merlo17** [comment]
Maybe "find Vanilla's most magical mob, brewing spells (deep in the swamp if we feel like that's clear enough, or something else to end the line)

**Comment by TemperedFool** [comment]
What, is my MacBeth reference too obscure? 😂

**Comment by NillerMedDild** [comment]
... Yes 😄

**Comment by TemperedFool** [comment]
For those who are curious: https://en.m.wikipedia.org/wiki/Three_Witches

**Pull request merged**
