### PR TITLE
Add ways to obtain various BYG nether items such as mushrooms

### LINKED ISSUE #2468: [0.5.0] Soul Shroom
**Modpack version**
0.5.0
**Describe the bug**
With the removal of BYG biomes from the nether there is no apparent way to get a Soul Shroom in new worlds. The Soul Shroom is used by the BooBee as its only "flower".

While the Market from Farming for Blockheads does contain BYG saplings it does not contain the Soul Shroom.

### PR DESCRIPTION
**Pull request by MuteTiefling**
Adds recipes to obtain warped coral and cactus, nether only BYG mushrooms, and sythian stalks.

Resolves #2468

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Nice! Warping is such a cool recipetype :P

**Comment by NillerMedDild** [comment]
Changed to Enhancement so the changelog generator picks up on it 👍

**Comment by MuteTiefling** [comment]
Ah right, sorry. thought it would get maintenance too :(

**Comment by NillerMedDild** [comment]
No worries. Maintenance and development is ignored, but I can add Maintenance to the list now that we actually have Development :P

**Pull request merged**
