### PR TITLE
Bees with PhD's

### PR DESCRIPTION
**Pull request by TemperedFool**
Basic Bee gating behind Nature's Aura (per Gates quest chapter). Move T1 Hive recipe override from base to normal. Add expert T1 recipe to kubejs/server_scripts/enigmatica/kubejs/expert/recipes/shaped.js - utilizing Gold Powder from NA to enforce gating. Add expert override for Apiary Breeder - requires Token of Joy from NA.

I've also taken the opportunity to add the next batch of magic bees - Starry for Astral Sorcery, Bloody Bee for Blood Magic, Infused/Tainted/Sky Bees for Nature's Aura. Next PR will be adding some recipes for these - likely starting with NA - but after seeing what @MuteTiefling did in #2173 for the Altar of Birthing recipes, I wanted to make more combs available ASAP!

Edit: Realizing I totally took screenshots and meant to include them. Will do so in the AM.

### CODE REVIEW

**Comment by TemperedFool** [comment]
Pictures as promised. T1 Hive:

image

Apiary Breeder - flowers are any minecraft:flowers:

image

**Comment by TemperedFool** [comment]
Centrifuge Recipes!

Centrifuge:
image

Centrifuge Casings:
image

Centrifuge Controllers:
image

**Comment by TemperedFool** [comment]
Elite Centrifuge Casings - Occultism Iesnium Ingot:
image

Elite Centrifuge Controller - Occultism Iesnium Ingot, PNC Advanced PCB, IF Advanced Frame:
image

**Comment by NillerMedDild** [comment]
Looks great :D It's likely that the Centrifuge recipes will need tweaking when I get to work on tech progression, but this is a solid start. I'd maybe relax a bit on the Iesnium though.

**Comment by TemperedFool** [comment]
Ooooh, I just realized I also made the casing recipe 1 per craft; default is 3, and was planning to make it 4 or 6.

Do you want me to completely cut the Iesnium, cut down the amount, or Will cutting the number of crafts required 4 or 6 times get the job done? If I cut it I can swap in something else.

**Comment by NillerMedDild** [comment]
Ah if it was meant to output more then I'm happy :D It was just the 4:1 ratio that seemed harsh.

> Do you want me to completely cut the Iesnium, cut down the amount, or Will cutting the number of crafts required 4 or 6 times get the job done? If I cut it I can swap in something else.

Option 3 to be clear :D

**Comment by TemperedFool** [comment]
Ok, going to go with 4 per craft as it should make an even number of crafts to make a centrifuge.

**Comment by TemperedFool** [comment]
Adjusted to 4 per craft:

image

image

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
