### PR TITLE
[Expert] Storage Drawers

### PR DESCRIPTION
**Pull request by MuteTiefling**
Starting off with a tweak to Mek Auto crafter. This give a semi early auto crafting option that's easily paired with Pretty Pipes to help with pre RS automation. I went with this over the Thermal one for early game as it is slower and upgrades are very far away. So it's just a slow little crafter for early game wheras Thermal or RFtools become available later and are faster. 

Crafter
image

Recipe patterns
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Upgrades
image

image

image

image

image

Framed Drawers:
image
image
image


Regular Drawers
image
image
image

Upgrade Templates
image

Void
image

Compacting
image

Controller
image

Slave
image

**Comment by NillerMedDild** [comment]
Very nice recipes so far 👌

**Comment by MuteTiefling** [comment]
Cool thanks. Thought I was going to have more for this. Only other thing would be possibly adjusting the total capacity down. But I think they're probably fine where they are with the new cost.

**Comment by NillerMedDild** [comment]
> Cool thanks. Thought I was going to have more for this. Only other thing would be possibly adjusting the total capacity down. But I think they're probably fine where they are with the new cost.

Agreed 👍

**Pull request merged**
