### PR TITLE
Bloody & Starry Bee

### PR DESCRIPTION
**Pull request by TemperedFool**
Further implement these bees:

1. Implement crafting recipes (Blood Altar and Starlight Crafting respectively) for their eggs.

image

image

2. Add uses for their combs - Bloody combs are going to the centrifuge currently, Starry combs can be used with Astral processes.

image
*Note the 0% chance for slates is because it is less than 1%.

image

image

image

Took the opportunity to stick in 2 QoL fixes - added Life Essence to the Kube lang file, and adjusted the laser ore drill recipe for Aquamarine Shale.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Hmm, I'm not seeing the Astral code?

**Comment by TemperedFool** [comment]
hmm, that works better when I actually push the last commit up... should be good now I think.

**Comment by NillerMedDild** [comment]
I feel like the Bloody Comb centrifuge recipes and Starmetal recipes could be more generous tbh. 

Perhaps 10% Ambule chance, 3% Slate chance, 3x output of Starmetal?

**Comment by TemperedFool** [comment]
You're absolutely the boss. I haven't done any balance testing, and clearly my instinct is to err on the stingy side. Commit incoming.

**Comment by NillerMedDild** [comment]
Great stuff, thanks :)

**Pull request merged**
