### PR TITLE
[Expert] IF Machine Shuffle

### PR DESCRIPTION
**Pull request by MuteTiefling**
Efficiency 1
image

Efficiency 2
image

Speed 1
image

Speed 2
image

Processing 1
image

Processing 2
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Plant Fertilizer
image

Hydroponic Bed
image
Want to make the in world farming stuff a little bit earlier than the rest. 

Same with some utility blocks like the mob detector and enchantment sorter. 
Mob Detector
image

Enchantment Sorter:
image

Potion Brewer:
image

**Comment by BooBeerb** [comment]
though, hydroponic beds with ether gas may potentially be the best farming method, i'm not sure if the fluid laser drill got shuffled yet

**Comment by MuteTiefling** [comment]
Ether gas would be significantly later than this is available, yeah.

**Comment by MuteTiefling** [comment]
First tier black hole tank/unit brought forward
image

image

**Comment by MuteTiefling** [comment]
Enchantment Extractor:
image

Marine Fisher:
image
Gotta do some manual fishing to get one going.

**Comment by MuteTiefling** [comment]
Random Ars Spellbook change, as discussed: 
image

Pink Slime Ingot
image

**Comment by MuteTiefling** [comment]
IF Ore Processing Washing:
image

Fermentation
image

Sieving:
image

**Comment by MuteTiefling** [comment]
Material stonework factory
image

Stasis Chamber:
image

Slowness module needs turtle, so the altar of birthing ritual is changed to summon without the need of a scute:
image

Mob Crusher
image

Black Hole Controller: Moved this a bit earlier to give a nice alternative for Drawer Controllers
image

Infinity Charger
image

Enchantment Factory:
image

Enchantment Applicator
image

**Comment by MuteTiefling** [comment]
Mob Duplicator

image

Mob Imprisonment Tools
image

Wither Builder
image

**Comment by MuteTiefling** [comment]
Mechanical Dirt: 
image
Can change the dirt to rich soil if nethers delight doesn't stick around.

**Comment by MuteTiefling** [comment]
Simplifying more of the in world farming stuff. 

Sewer
image

Sewage Composter
image

**Review by NillerMedDild — APPROVED** [review]

**Comment by MuteTiefling** [comment]
Baby Animal Yeeter
image

Rancher:
image

Alt recipes for first 3 range addons so the few machines that have been brought forward are somewhat useful:
image

image

image

**Comment by MuteTiefling** [comment]
Gonna stop this one here. Might not have a lot of time this weekend. 

Still have a few more machines to look at. Might update the range addons.

IF Power still needs a pass. Machines are all very cheap to run, for the most part. Also thinking of putting all of the mycelial generators kinda late and giving them a decent buff.  The mycelial reactor itself will likely be a big magic/tech craft that places it after or about the same time as mek fusion.

**Comment by NillerMedDild** [comment]
> IF Power still needs a pass. Machines are all very cheap to run, for the most part. Also thinking of putting all of the mycelial generators kinda late and giving them a decent buff. The mycelial reactor itself will likely be a big magic/tech craft that places it after or about the same time as mek fusion.

Big thumbs up for this 😄

**Pull request merged**
