### PR TITLE
Added automation for Building Gadgets construction paste

### PR DESCRIPTION
**Pull request by Merlo17**
Fixes https://github.com/NillerMedDild/Enigmatica6/issues/1128

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Your AIOT recipe made it into this PR too :P

**Comment by hvdklauw** [comment]
haha funny, we are working on adding this ourselves to building gadgets :)

**Comment by Merlo17** [comment]
Oh sssshit, I just stages all new files without noticing

Maybe comment that out for now, there's still that weird reload issue I reported to max. By default it's all fine but if you /reload aiot recipes break. Your call

**Comment by NillerMedDild** [comment]
> Maybe comment that out for now, there's still that weird reload issue I reported to max. By default it's all fine but if you /reload aiot recipes break. Your call

Done!

**Review by NillerMedDild — COMMENTED** [review]
Looks very good!

**Pull request merged**
