### PR TITLE
Remove unwanted unicode replacement characters

### PR DESCRIPTION
**Pull request by Quezler**
i actually came here to fix a typo in the readme, but its uneditable due to a maelstrom of unicode chars:

Screen Shot 2020-11-10 at 19 20 32
Screen Shot 2020-11-10 at 19 20 51
Screen Shot 2020-11-10 at 19 22 15

> this commit only removes all occurrences of that one [character](https://www.fileformat.info/info/unicode/char/fffd/index.htm), actual typo pull request will follow once merged 🤔

### CODE REVIEW

**Comment by NillerMedDild** [comment]
The file you changed isn't the rendered README - Does this one also cause issues for you? https://github.com/NillerMedDild/Enigmatica6/blob/master/.github/README.md

**Comment by Quezler** [comment]
yea that one renders fine 🤔 

(i had no idea one could hide a readme in the .github directory, i thought only the root one mattered)

**Comment by Quezler** [comment]
since 48b5a8edcb2d4528d8da772ca20e8b0587800f45 removed the file this pr changes, ima close it 😗 (still a weird bug)

**Comment by NillerMedDild** [comment]
Yeah it's super weird :P it rendered fine for me to make it even weirder.

**Pull request closed without merging**
