### PR TITLE
Added convenient recipes for drawers using every wood type

### PR DESCRIPTION
**Pull request by Merlo17**
Should fix https://github.com/NillerMedDild/Enigmatica6/issues/1573, although I feel like an info tab to explain how framed drawers work could still be useful

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Have you tested whether this overrides recipes for other vanilla wood type drawers? :)

**Comment by NillerMedDild** [comment]
And I agree JEI info would be very useful here.

**Comment by Merlo17** [comment]
They showed up in JEI, it shouldn't override because of that return at the beginning no?

**Comment by NillerMedDild** [comment]
Ah right my bad, I didn't see that in the PR overview.

**Pull request merged**
