### PR TITLE
Schematics for the Create Schematicannon

### PR DESCRIPTION
**Pull request by TemperedFool**
This is the first time I've ever worked with Github beyond submitting issues, so please bear with me. I think I've done this right? Let me know if I haven't!

This is a batch of Create Schematics, mirroring the existing building_gadgets_patterns folder. I've included a README.txt to help explain how the schematics work; none of them will show up in-game by default, but if they are copied back to the root schematics folder (clientside), they will be available in-game at the schematic table. Nice to have an alternate method to the Building Gadget, per a discussion I had with Motoko on Discord.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks great, thank you :D
I wonder, how crowded would it look in-game if the schematics were all available by default? I'm thinking these would be far easier to discover if they're available by default. We could always just prefix the modname.

**Comment by TemperedFool** [comment]
It shows up in-game as a list you scroll with your scroll wheel. It's a lot of schematics, but if they're prefixed with the mod name it may look fine. I'll set it up later today and see how it looks, and post a screenshot if it looks iffy.

**Comment by TemperedFool** [comment]
So, investigated a little. Putting the full name in results in a pretty significant overrun of the table interface:

image

Probably best not to do that. I did go ahead and abbreviate everything, and it ends up looking like this:

image

I think that looks ok? The lack of alphabetical sorting is infuriating, to the point that I've put in an issue:

https://github.com/Creators-of-Create/Create/issues/1192

If you like it this way, do I just close out this PR and submit a new one? Github newb here ^_^

**Comment by MuteTiefling** [comment]
Any changes you push to your dev branch will be mirrored here until this has been merged. So you can just make changes and push again

**Comment by TemperedFool** [comment]
Ha ha! Learning things the brute-force way is fun. I'll push it up shortly.

**Comment by TemperedFool** [comment]
I think that should do it then?

**Comment by NillerMedDild** [comment]
Nicely done, thank you! 👍

**Pull request merged**
