### PR TITLE
Atum - Bringing some life

### PR DESCRIPTION
**Pull request by MuteTiefling**
Adds the following to Atum
Crocodiles
Emu
Bald Eagles
Flies
Gazelle
Gusters
Komodo Dragons
Rattlesnakes
Road Runners
Sunbirds
Tarantula Hawks

Many additional drops added to crate loot, including animal products such as pelts, food, and precious metals.

### CODE REVIEW

**Comment by telemenar** [comment]
Right now I like the minimal level of wildlife as it makes it so much easier to find rabbits. Which are pretty rare in the overworld.

**Review by NillerMedDild — APPROVED** [review]

**Comment by MuteTiefling** [comment]
> Right now I like the minimal level of wildlife as it makes it so much easier to find rabbits. Which are pretty rare in the overworld.

We've got some added features to help find bunnies still, and they're still fairly common even with the extra wildlife in atum. 

You'll also find their pelts/feet fairly commonly in the atum crates now.

**Comment by MuteTiefling** [comment]
Loot crates now 42% more interesting :D

Think this one is all set.

**Comment by NillerMedDild** [comment]
42!!! Very nice!

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
