### PR TITLE
Reverse-stonecutting

### PR DESCRIPTION
**Pull request by Rodg88**
Added ability to use the stonecutter to switch between different variants of stones, eg from bricks to pillars. Mod compatability with Quark, Create, (some)Embellishcraft, PNC, Botania, Ars Nouveau, and Blood Magic.

### CODE REVIEW

**Comment by Rodg88** [comment]
Not auto-generated as only some of the block variants in a stone type I wanted to be used as a source, so it's hand-curated. Also I'm not a coder lol

**Comment by Merlo17** [comment]
It looks pretty nice but I would probably use a foreach loop to clean it up a bit :P

**Comment by Rodg88** [comment]
Yeah well that requires some knowledge of how to do them :P lol If you have examples I can try tidy it up a bit, at least for the bigger lists. 

I also noticed astral marble to quark marble conversion wasn’t working, so I added that in as simple recipes that just swap between the base blocks. I quite liked how it worked not having astral marble variants visible if I’m currently working on quark marble, but still being able to swap between them by going via the plain stone variant.

**Comment by Merlo17** [comment]
I'd look at all of our other recipe examples :P the structure is pretty clear there I'd say. Tell me if you need anything ^^

**Comment by Rodg88** [comment]
Looking at it, it seems a bit complicated and all new to me so would take a while, and not sure it would even save any lines of code. Due to the requirement of only specific stone variants being desired inputs, it'd still need a list of each item type I've picked for a loop to go through? I think it's partly why Niller said here it'd be a time consuming manual task to do this lol: https://github.com/NillerMedDild/Enigmatica6/issues/1342

I could separate out the recipe deletions, it just made it simpler to keep the deletions next to the additions for each stone type to keep track of the tweaks

**Comment by NillerMedDild** [comment]
I don't mind going over it and converting it to loops and such :)

**Pull request merged**
