### PR TITLE
Add Tinkers Construct Quest Line and Loot Tables

### PR DESCRIPTION
**Pull request by mcilhargey**
Add a Tinkers quest line to educate/reward building in the tinkers line. This quest line has it's own loot tables based on items in the mod itself.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks good from what I've read so far 👍 
I would however like the slime island quests to not be checkbox based, perhaps they could be merged to be one per dimension, and just require the saplings and such?

**Comment by theboo** [comment]
got home late from work today, ill look through these tomorrow

**Review by theboo — COMMENTED** [review]
no description in "puny smelting" task, as i dont know tinkers 1.16 well at all, unsure if this is intended
image

checkmark quest for tinkers upgrade, is there an advancement for your first applied upgrade that might be able to be used instead?
image
same question here:
image

If one of the books has info on what the various frames' effects are, you might mention that here?
image

**Comment by KnightMiner** [comment]
> checkmark quest for tinkers upgrade, is there an advancement for your first applied upgrade that might be able to be used instead?

You an easily create an advancement that checks for a tinker tool having one of a list of modifiers. The syntax is rather verbose, but look into the TiC "ability master" advancement or the "upgrade slots" advancement.

**Comment by MuteTiefling** [comment]
If they're advancements, we can actually just watch for those.

**Comment by KnightMiner** [comment]
The advancements don't do exactly what you want the ones I mentioned are for applying all modifiers from a particular set, not applying just 1

**Review by theboo — COMMENTED** [review]
looks good to me!!

**Comment by NillerMedDild** [comment]
Woohoo \o/

**Pull request merged**
