### PR TITLE
Bees QOL

### PR DESCRIPTION
**Pull request by TemperedFool**
A few different QOL things for Bees:

Recipes for the world-gen Bee Nests from RBees. They require specific world-gen bee's combs, and all follow a similar format to this one (which is the Oak Bee Nest):

image

Adds extra spawning for a few bees - Beeper, Slimy, and Zombee to Undergarden, Sandy to Atum, Skeleton to Nether. Should make it a little easier to find these bees, and seems on-theme for them.

Reduces Mutation Count per pollination for most bees to 4. We're finding that mutation is a bit too powerful, so pulling back the number of mutations possible before going back to the hive should help with that.

Overall Mutation Adjustment. Removing stone tag, and using a mix of cobblestones - vanilla, andesite, diorite, granite - and polished_basalt for nether stuff. Products are the appropriate stone ore.

Adjusts Emerald Combs to produce prismarine shards as a secondary, rather than uranium ingots.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Nice changes! Would you mind adding the changes to the changelog? 
It's in `changelog/CHANGELOG.md`, these would go under `Changes/Improvements`.

**Comment by NillerMedDild** [comment]
Why did you go for cobblestones for mutations instead of plain stones?

**Comment by MuteTiefling** [comment]
The idea was to reduce accidental in world mutations. So all the mutation targets are things that don't occur naturally.

**Comment by TemperedFool** [comment]
> Nice changes! Would you mind adding the changes to the changelog? 
> 
> It's in `changelog/CHANGELOG.md`, these would go under `Changes/Improvements`.

Absolutely, will get it done in the morning.

**Comment by TemperedFool** [comment]
That should do it! I THINK I formatted everything correctly...

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Perfect ty 👌

**Pull request merged**
