### PR TITLE
Add Aquamarine Shale IF Ore Laser Recipe

### LINKED ISSUE #1932: Aquamarine From IF laser drill?
Aquamarine shale could be added to the IF laser drill as a way to produce aquamarine without a starlight sand gen, which can be quite laggy. It could be a cyan lens ore rarer then apatite. And since the IF fluid lasers can make starlight anyway, there doesn't seem to be much reason not to be able to get aquamarines from the ore lasers too

### PR DESCRIPTION
**Pull request by TemperedFool**
Added tags for Astral Aquamarine Shale to forge:ores, and added a recipe for the IF Ore Laser.

Re-enabled the nether_end_biomes combo tag so I could blacklist both.

Added Starmetal Ore to blocks/forge/ores.js while I was already tinkering with it.

Closes #1932.

### CODE REVIEW

**Comment by sciguyryan** [comment]
Something I noticed in that: you have this line twice:

`type: 'industrialforegoing.laser_drill_ore',`

**Comment by TemperedFool** [comment]
> Something I noticed in that: you have this line twice:
> 
> `type: 'industrialforegoing.laser_drill_ore',`

Is this lines 1096 and 1126? I used the same format as every other recipe in the file - copy/pasted actually. They all have the double-type line.

**Comment by sciguyryan** [comment]
Yes, that would be the one.

You are correct. They all seem to have that same issue. Not that it really
matters anyway, just something my editor picked up when I loaded up the
file.

Cheers,
Ryan Jones-Ward

"Life is a game that deals in the currency of entropy. The game is played
by biological machines programmed in the languages of physics and
chemistry: machines of astounding complexity and sophistication, able to
achieve the extraordinary and impossible and yet... it's all just a game."

life←{↑1 ⍵∨.∧3 4=+/,¯1 0 1∘.⊖¯1 0 1∘.⌽⊂⍵}

**Comment by TemperedFool** [comment]
@NillerMedDild If you want me to delete these redundant "type" lines (if they are actually redundant?) I can do so.

**Review by NillerMedDild — APPROVED** [review]
Looks good to me, thanks!

**Comment by MuteTiefling** [comment]
this whole code block probably needs a cleanup, honestly.

**Comment by NillerMedDild** [comment]
That it does, I'll give it quick once-over.

**Pull request merged**
