### PR TITLE
Powah Rebalance

### PR DESCRIPTION
**Pull request by MuteTiefling**
Starter tier of everything is removed. These are so low powered as to not be worth crafting, yet bringing them up while leaving other options in place makes those tiers feel worse by comparison.

All non reactor generators have had their power buffers reduced.

# Thermo Generators
Narrowed the generation gap, significantly boosting the low end while bringing the high end to a more reasonable rate.
Introduced two new coolants: I-C Bee Honey and Ether Gas.
Though only I-C Bee Honey will be of much use here as a result of the output caps in place on these generators.

| Water Cooled | Lava   | Magma  | Blazing Block | Nitro Block | Extraction Cap |
|--------------|--------|--------|---------------|-------------|----------------|
| Basic        | 57     | 68.4   | 159.6         | 456         | 3120.0         |
| Hardened     | 64     | 76.8   | 179.2         | 512         | 4190.0         |
| Blazing      | 73     | 87.6   | 204.4         | 584         | 5260.0         |
| Niotic       | 80     | 96     | 224           | 640         | 6330.0         |
| Spirited     | 87     | 104.4  | 243.6         | 696         | 7400.0         |
| Nitro        | 94     | 112.8  | 263.2         | 752         | 8470.0         |
| IC Cooled    |        |        |               |             |                |
| Basic        | 642.0  | 770.4  | 1797.7        | 5136.2      | 3120.0         |
| Hardened     | 720.9  | 865.0  | 2018.4        | 5766.9      | 4190.0         |
| Blazing      | 822.2  | 986.7  | 2302.3        | 6577.9      | 5260.0         |
| Niotic       | 901.1  | 1081.3 | 2523.0        | 7208.7      | 6330.0         |
| Spirited     | 979.9  | 1175.9 | 2743.8        | 7839.4      | 7400.0         |
| Nitro        | 1058.8 | 1270.5 | 2964.6        | 8470.2      | 8470.0         |

# Solar Panels
Due to the simplicity of running Solar, these are being brought a little lower. Like Thermo, the low end has been raised to make the entry level more useful, while the top tier has been reduced.

| Basic    | 220 |
|----------|-----|
| Hardened | 320 |
| Blazing  | 420 |
| Niotic   | 520 |
| Spirited | 620 |
| Nitro    | 720 |

# Magmators and Furnators
No changes. These can be considered burst power sources as a single piece of fuel is always worth the same amount of energy. Higher tiers simply burn it faster with no efficiency gains or losses.

# Reactors
These have been given a 50% boost in overall production value. The inclusion of better coolants also allows them to run much more efficiently, stretching fuel even further.

For comparison the reactors below had dry ice, coal, redstone, and were provided 8 pieces of uraninite.
### Pre Buff:
Water Cooled Nitro Reactor = generates 72 million RF @ ~84k rf/t per uraninite

### Post Buff:
Water Cooled Nitro Reactor = generates 106 million RF @ ~125k rf/t per uraninite
I-C Cooled Nitro Reactor = generates 143 million RF @ ~125k rf/t per uraninite
Ether Cooled Nitro Reactor = generates 350 million RF @ ~125k rf/t per uraninite

One thing to note here, the liquid coolant is not consumed in Reactors, unlike Thermo Generators. So while Thermo generators need some light automation to keep the IC honey flowing for cooling, reactors do not. They instead only need the ice/coal/redstone automated.

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Not quite sure I'm happy with these numbers just yet. Overall, Solar and Thermo have been given a linear scale, rather than exponential. This seems to work better for Thermo given the boost from different coolants, but for Solar it feels a little plain.

**Comment by NillerMedDild** [comment]
Those Nitro Solar Panels are ridiculously expansive O_o I think they should generate at least 4096 rf/t or have their cost reduced.

I need to fiddle some in-game before commenting on other values :)

**Comment by MuteTiefling** [comment]
Cool. I was thinking one of two possibilities for bringing costs down. 

1) As mentioned, make each solar cost only one of the previous tier. Currently they're 3:1
2) Solar (and all other generators) are given new recipes that are not tiered crafts. Reactors, cables, and ender gates do this already. So a nitro solar would cost 2 nitro capacitors, 3 nitro crystals, a casing, and 3 photovoltaic panes. 

If we go option 2, a second craft would also be nice that allows you to upgrade. So any tier of a generator could be recrafted to any other tier. In the case of solar, that would look something like 1 solar + 2 capacitors and 3 crystals of the new tier.

**Comment by NillerMedDild** [comment]
I'm partial to solution 2, but that also requires far more work than 1 :P

**Comment by MuteTiefling** [comment]
That's ok. I'm willing to do it :D

**Comment by NillerMedDild** [comment]
In that case please do so :D

**Comment by NillerMedDild** [comment]
In regards to Thermo, I think the low-end is too high and high-end is too low :P I would probably half and double. It also seems to me like the Nitro Block is simply too powerful, and should be reduced ~30%

**Comment by MuteTiefling** [comment]
Ok. Can adjust. Where would you like the top end on thermo?

**Comment by NillerMedDild** [comment]
| Water Cooled | Lava   | Magma  | Blazing Block | Nitro Block | Extraction Cap |
|--------------|--------|--------|---------------|-------------|----------------|
| Basic        | 57     | 68.4   | 159.6         | 456         | 3120.0         |
| Hardened     | 64     | 76.8   | 179.2         | 512         | 4190.0         |
| Blazing      | 73     | 87.6   | 204.4         | 584         | 5260.0         |
| Niotic       | 80     | 96     | 224           | 640         | 6330.0         |
| Spirited     | 87     | 104.4  | 243.6         | 696         | 7400.0         |
| Nitro        | 180     | 200  | 300         | 400         | 8470.0         |
| IC Cooled    |        |        |               |             |                |
| Basic        | 642.0  | 770.4  | 1797.7        | 5136.2      | 3120.0         |
| Hardened     | 720.9  | 865.0  | 2018.4        | 5766.9      | 4190.0         |
| Blazing      | 822.2  | 986.7  | 2302.3        | 6577.9      | 5260.0         |
| Niotic       | 901.1  | 1081.3 | 2523.0        | 7208.7      | 6330.0         |
| Spirited     | 979.9  | 1175.9 | 2743.8        | 7839.4      | 7400.0         |
| Nitro        | 1800 | 2000 | 3000        | 4000      | 8470.0         |

**Comment by MuteTiefling** [comment]
oooh, I was understanding the opposite. Ok, should be easily done.  Will work on this and recipe changes tonight.

**Comment by MuteTiefling** [comment]
Thermo Generator tweaked as discussed. Increased low end, decreased high end.

New Rates as follows:

| Water Cooled | Lava | Magma | Blazing Block | Nitro Block | Extraction Cap |
|--------------|------|-------|---------------|-------------|----------------|
| Basic        | 130  | 156   | 221           | 286         | 2419.0         |
| Hardened     | 140  | 168   | 238           | 308         | 2739.0         |
| Blazing      | 150  | 180   | 255           | 330         | 3059.0         |
| Niotic       | 160  | 192   | 272           | 352         | 3379.0         |
| Spirited     | 170  | 204   | 289           | 374         | 3699.0         |
| Nitro        | 180  | 216   | 306           | 396         | 4019.0         |
| IC Cooled    |      |       |               |             |                |
| Basic        | 1319 | 1583  | 2243          | 2902        | 2419.0         |
| Hardened     | 1421 | 1705  | 2415          | 3126        | 2739.0         |
| Blazing      | 1522 | 1827  | 2588          | 3349        | 3059.0         |
| Niotic       | 1624 | 1948  | 2760          | 3572        | 3379.0         |
| Spirited     | 1725 | 2070  | 2933          | 3795        | 3699.0         |
| Nitro        | 1827 | 2192  | 3105          | 4019        | 4019.0         |

All Powah crafts, except the Player Transmitter, have been made non-tiered recipes.

The reason for leaving the Player Transmitter is two fold. First, you're unlikely to ever craft more than one. Two, Flux Networks is gated behind that craft.

All of these recipes now have an 'upgrade' recipe that effectively takes any tier, replaces the capacitors/crystals, and gives you a new tier. Some care should be taken as this can downgrade tiers too.

All Reactors now have a 1:1 shapeless craft to help people reset NBT in the odd case that their reactor doesn't break down cleanly. Have seen at least one case on Discord where they player could no longer construct their reactor because the reactor blocks would no longer stack. This would allow the player to self correct.

Lastly, I moved the arrays for the Powah tags out into Constants to facilitate these recipes.

**Review by NillerMedDild — APPROVED** [review]

**Comment by MuteTiefling** [comment]
Cool, all added to the wiki!

**Pull request merged**
