### PR TITLE
Add Building Gadgets Patterns for Compact Crafting

### PR DESCRIPTION
**Pull request by Mendanbar**
- Adds Patterns for the 6 different machine sizes, as well as the max field projection setup (needed to craft all of them)

### CODE REVIEW

**Comment by Mendanbar** [comment]
Hoping this eases some pain points while we wait for https://github.com/NillerMedDild/Enigmatica6/issues/1534 to be fixed.

**Comment by NillerMedDild** [comment]
Did you verify these in-game? :)

**Comment by Mendanbar** [comment]
Just checked in 0.4.3 and I'm seeing some interesting behavior.  Field projector paste works fine, but the only way I can get the machines to craft consistently is by leaving one machine wall out of the copy-paste, and then placing it by hand before throwing in the catalyst.  Something about dropping in the whole structure at once causes it to not be recognized. 🤷‍♂️ 

I can update the recipes to have one missing machine wall block, and include a readme to explain some of the quirks.  Would that be ok?

**Comment by NillerMedDild** [comment]
Hmm, yeah that's fine for now, thank you :)

**Comment by Mendanbar** [comment]
Updated.  It's working very consistently now in all of my tests using the steps in the readme.

**Comment by TemperedFool** [comment]
I will snag these and mess with them with the Schematicannon. Would be interesting to see if it behaves a bit better, since it places the structure block by block. I'll submit a PR with them after.

**Comment by NillerMedDild** [comment]
Nice work, thank you for your contribution :D

**Pull request merged**
