### PR TITLE
Mythic Botany Text changes

### PR DESCRIPTION
**Pull request by MuteTiefling**
Reworded the entries to flow a bit better, clarifying the language and fixing errors.

Also removed the text stating that Gaia Pylons are crafted from Alfsteel Pylons to match the recipe change and tagged the entries for the generating flowers as being intentionally removed.

Even before these changes, I noticed that the most recent commit seems to have introduced an issue with the patchouli book. The following entries no longer work:

Alfsteel Mana Bands
Alfsteel Pylons
Functional Flora
Ring of Muspelheim

Removing all KubeJS scripts resolves this. Not sure what the exact issue is there... maybe something to do with the recipe changes?

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Thanks! Did you verify this in-game?

> Even before these changes, I noticed that the most recent commit seems to have introduced an issue with the patchouli book. The following entries no longer work:

Alfsteel Mana Bands
Alfsteel Pylons
Functional Flora
Ring of Muspelheim

I guess removing recipes for those two flowers broke the entries :s not sure why though. Maybe we need to remove the book entries for those flowers as well.

**Comment by MuteTiefling** [comment]
Yep, the changes were working except those couple of pages. I can mess with it some more to see if I can figure out why those couple entries broke too

**Comment by NillerMedDild** [comment]
Yes please :p I looked at the files and that didn't help much.

**Comment by MuteTiefling** [comment]
Alright, so removing these lines from the global disable fixed the issue with the broken entries:

```
    'mythicbotany:raindeletia',
    'mythicbotany:raindeletia_floating',
    'mythicbotany:wither_aconite',
    'mythicbotany:wither_aconite_floating',
```

However, all attempts to change the layout of the patchouli book have failed so far. KubeJS will gladly replace the lang files and insert my altered text, but the layout itself is resisting me. I feel like I might have the files in the wrong path somehow...

**Comment by MuteTiefling** [comment]
Got a few more things to test, but according to someone on the kjs discord, patchouli is just hard coded to look at the mod resources, so it might not be possible to override this... 

We might just need to live with a broken book.

**Comment by NillerMedDild** [comment]
Oh, damn... I'm gonna try replacing the MythicBotania flower recipes with an empty JSON, see if that helps.

**Comment by MuteTiefling** [comment]
lol, seems we both had a similar idea. I just pushed another commit to my repo that fixes this completely

**Comment by NillerMedDild** [comment]
Ha nice :D

**Comment by NillerMedDild** [comment]
Hmm, I didn't manage to fix it, would you mind sending me your change or PR'ing it? :)

**Pull request merged**
