### PR TITLE
repurposed structures preset, with some structure changes

### PR DESCRIPTION
**Pull request by theboo**
made villages slightly more common, dungeon crawl dungeons a bit more common, astral temples slightly less common. Tried adjusting towers of the waild but thats gonna require a config change, these dont seem to affect it... this wont have to be changed if we decide to not use repurposed structures as they will be removed from config on first load without the mod installed

### CODE REVIEW

**Comment by Merlo17** [comment]
We should probably axe mineshafts since we have YUNGs no?

**Comment by theboo** [comment]
yeah, i dont think they do anything anyway with yungs installed, but we can look at it

**Comment by theboo** [comment]
this might need to wait until next breaking update yes? if so we can close it as i wouldnt set these until closer to update time

**Comment by NillerMedDild** [comment]
Only the biome weights need to wait, I'm fairly certain we can alter structure generation in a patch version with no issues :)

**Comment by theboo** [comment]
@NillerMedDild idk if it is possible to merge just part of a PR, but the towers of the wild config and new TF preset for repurposed structures can be added to dev with no issues

**Comment by NillerMedDild** [comment]
It's not :/ I'll save a temp file and overwrite

**Pull request merged**
