### PR TITLE
Betterend compat

### PR DESCRIPTION
**Pull request by Merlo17**
Big batch of compat, mentioned here https://github.com/NillerMedDild/Enigmatica6/issues/1276

only note is I couldn't add every alloy recipe to the smelter, since the recipes only accept a single item as input, so for example bronze which is 3+1 couldn't be added.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Great stuff! The majority of `betterend/alloying.js` would be better suited as part of the `unify_materials.js` script - The one that adds gears, ore processing and the like. Would you like to take a crack at it? :)

**Comment by Merlo17** [comment]
sure, I will have a look later tonight ^^

**Comment by Merlo17** [comment]
Should be all done! Along the way I also noticed IE ores weren't hidden in JEI so I fixed that and pushed to the wrong branch so now it's in the PR and you're gonna like it :P

**Comment by NillerMedDild** [comment]
> I also noticed IE ores weren't hidden in JEI so I fixed that

They're hidden with regex :P

**Comment by Merlo17** [comment]
Are you sure? I couldn't find it in the regex array and they were unhidden on the first launch without reloads

**Comment by NillerMedDild** [comment]
Did you forget to pull perhaps? They're in the regex array, line 177

**Comment by Merlo17** [comment]
Huh, I knew I had to go get new glasses, better go tomorrow :P

**Pull request merged**
