### PR TITLE
Update squeezer.js

### PR DESCRIPTION
**Pull request by DarkAngel22579**
Cleaned up squeezer recipes to match the updated fermenter recipes.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks good, thanks :D

If you're up for it, perhaps change it to a single json object, in the form:
```json
const recipes = [
{ inputs: ['...'], value: 20 }, { inputs: ['...'], value: 40 }
];
```
Best of both worlds then :D these values vary a bit more than the Fermenter ones, so it makes more sense to use a json structure over simple arrays.

**Review by NillerMedDild — APPROVED** [review]
Great work, thank you :)

**Comment by DarkAngel22579** [comment]
Had to take a detour and learn how objects and arrays work in javascript, but I got there in the end :D

**Comment by NillerMedDild** [comment]
Important detour :D

**Pull request merged**
