### PR TITLE
Revert "Allow ftb ultimine to harvest entire menril tree (excl. leaves)"

### PR DESCRIPTION
**Pull request by MuteTiefling**
was targetting master, oops

### CODE REVIEW

**Comment by Quezler** [comment]
rip, my bad, i guess i was too hurried in trying to make a working pull before someone else would beat me to it 😅

**Comment by MuteTiefling** [comment]
:D this is why I don't normally merge other people's PRs. Live and learn :D

**Comment by Quezler** [comment]
~~a bot that sends a warning message to new pulls that target the master branch sounds like something worth looking into~~

**Comment by MaxNeedsSnacks** [comment]
GitHub Actions could also just auto-close any opened PRs that target master don't have a certain title or tag (since Triage members can tag pull requests as they're opened, this shouldn't be an issue)

**Comment by MaxNeedsSnacks** [comment]
Or, better yet, they could just change the target branch to develop automatically ^^

**Pull request merged**
