### PR TITLE
Stonecutting cleanup

### PR DESCRIPTION
**Pull request by ochotonida**
I cleaned up the stone cutting scripts in an attempt to make them a bit more maintainable.
All cuttable blocks are defined in the `stonecuttables.js` script, from which tags and recipes are generated. For each item a new stonecutting recipe is generated with the relevant tag as the input, and any existing stonecutting recipes for the item are removed.

There's a good chance I've missed some stuff, so some review/testing is very welcome.

### CODE REVIEW

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Looks great, I'll verify/test in-game as well, thanks!

**Comment by NillerMedDild** [comment]
I checked around 30 different stones and all worked as except :D

**Comment by Rodg88** [comment]
Even byg red rock? That one was the most painful when I did it lol

**Comment by NillerMedDild** [comment]
I didn't check BYG Red Rock :P

**Pull request merged**
