### PR TITLE
Added processing recipes for Limesand to Silicon

### PR DESCRIPTION
**Pull request by Merlo17**
As suggested by https://github.com/NillerMedDild/Enigmatica6/issues/1257

I wasn't sure at first (and I'm still not entirely), but it does make sense to add a way to process silicon with create cobbleworks if the material stoneworks factory can do it too.
The automation chain is pretty long anyways, and it only has a chance to actually produce, so the smelting quartz way is still the preferrable route, but there is at least a create alternative that doesn't involve quartz.
Still up for discussion though

### CODE REVIEW

**Comment by NillerMedDild** [comment]
I like the Limesand recipe, I think it makes sense and I think it should be applied to Mekanism and Thermal as well. Will you do the honors? :)

**Comment by Merlo17** [comment]
Honored to do the honors! What concerns me slightly is that they probably don't have a way to make the output chance only... or can they? Will investigate

**Comment by MuteTiefling** [comment]
Thermal can do chance output. Mekanism cannot.

**Comment by Merlo17** [comment]
Just found out too, to implement that I increased the input count for those who can't do chance. Mek is 4 -> 1 for example

**Comment by OneLemonyBoi** [comment]
Maybe add an in-world crafting option via Interactio, which is more inefficient.

**Comment by Merlo17** [comment]
> Maybe add an in-world crafting option via Interactio, which is more inefficient.

how would you set up the craft? limesand into what?

**Comment by Merlo17** [comment]
Also I added mekanism and thermal recipes. I wanted to add IE and pedestals crushing recipes too, but unfortunately they don't support chance output or multiple inputs, so my only option would've been 1:1 and I still want to keep these recipes more expensive than the quartz ones, so no silicon for them :(

**Comment by OneLemonyBoi** [comment]
> > Maybe add an in-world crafting option via Interactio, which is more inefficient.
> 
> 
> 
> how would you set up the craft? limesand into what?

3:1 ratio for limesand to silicon.

**Comment by MuteTiefling** [comment]
Create Washing is basically that, but more interesting.

**Comment by Merlo17** [comment]
Agreed, I don't particularly think that it does anything either

**Comment by NillerMedDild** [comment]
I think 4 -> 1 is a bit harsh in the Mek Crusher, would you mind if I change it to 3?

**Pull request merged**
