### PR TITLE
Allow Ultimine to break Filled and Regular Menril logs

### PR DESCRIPTION
**Pull request by MuteTiefling**
Allow Ultimine to break Filled and Regular Menril logs. Allows chopping a whole menril tree at once like any other tree

.

### CODE REVIEW

**Comment by Quezler** [comment]
duplicate of (my) #3272 😅

**Comment by MuteTiefling** [comment]
yeah, lol was just seeing that

**Comment by Quezler** [comment]
(it would probably also have messed with [some recipes](https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.16/src/main/resources/data/integrateddynamics/tags/blocks/menril_logs.json) that were only intended for the normal log by the mod itself)

**Comment by MuteTiefling** [comment]
nah, that's why I left it on block tags. Recipes don't use those. But yours is safer still

**Pull request closed without merging**
