### PR TITLE
Tag updates

### PR DESCRIPTION
**Pull request by ochotonida**
I've updated Create's `upright_on_belt`, `fan_transparent` and `fan_heaters` tags with additional blocks/items, and I've added the heat sources to Farmer's Delight's cooking pot as well

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Totally going to steal some of this to update PNC and Powah heat sources too. Looks good from what I've seen

**Comment by TemperedFool** [comment]
Oooooh, Create's Fan quest needs a note that these tags exist if it doesn't already have it...

**Comment by ochotonida** [comment]
JEI doesn't allow you to search for block tags I'm afraid, but maybe we could add them as item tags as well

**Comment by TemperedFool** [comment]
Hmm, the redundancy is bothersome, but it would be really cool. With striking ignorance he asks: "how tricky is that actually?"

**Comment by MuteTiefling** [comment]
Create also has auto compat for certain types of blocks. Like open doors, trap doors, and glass panes that aren't connected on the sides. Basically à lot of partial blocks.

**Comment by NillerMedDild** [comment]
> Hmm, the redundancy is bothersome, but it would be really cool. With striking ignorance he asks: "how tricky is that actually?"

Not tricky, just annoying to maintain :P

**Review by NillerMedDild — APPROVED** [review]
Looks good to me!

**Pull request merged**
