### PR TITLE
Saw update

### PR DESCRIPTION
**Pull request by MuteTiefling**
Pedestals and Thermal to come soon.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Good stuff! 

If you use the same variable across multiple scripts, please place it in `constants.js` so they can share it :) that script has a very high load priority, so it will be available.

**Comment by MuteTiefling** [comment]
There's slight differences, but I'll see what I can do. It might require doing some form of blacklist in each script to avoid duplicate recipes since some of these things are covered natively

**Comment by NillerMedDild** [comment]
If it's more than 30 seconds of work don't bother :D I thought they were identical

**Comment by MuteTiefling** [comment]
Should be all set now :D

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Nice!!

**Pull request merged**
