### PR TITLE
[Expert] Feedback Tweaks

### PR DESCRIPTION
**Pull request by MuteTiefling**
Metal Bars moved from IE crafting
image

Spirit Attuned Gem, switch to source gems instead of shadow gems, greatly reducing the need to craft shadow gems. 
image

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Works for me 👌

**Comment by MuteTiefling** [comment]
image

**Comment by NillerMedDild** [comment]
Thank you kindly

**Comment by NillerMedDild** [comment]
I don't see the description commit in there?

**Comment by MuteTiefling** [comment]
forgot to push it >.<

**Comment by NillerMedDild** [comment]
no worries, I just did it :P

**Pull request merged**
