### PR TITLE
Industrial Foregoing Ore Laser Cleanup

### PR DESCRIPTION
**Pull request by MuteTiefling**
Removed Sapphire and Ruby as they are not used.
Added Dimensional Shards (Rates TBD)
Unified all possible ores on EE ore chunks
Brought all remaining ores in as scripts for future weight/distribution changes if desired.
Added appropriate tags to Yellorium to bring it into the Ore Laser in case reactors are staying.
Added Oil as a fluid that can be mined with the new fluid laser.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Great work, thank you!

**Comment by NillerMedDild** [comment]
One small note, please base future PRs on the develop branch so we can check out the changes on the dev server before merging :)

**Comment by Darkere** [comment]
If you realize before merging you can easily change the target branch 😄

**Comment by NillerMedDild** [comment]
I did not :D

**Comment by MuteTiefling** [comment]
I shall double check that next time. I actually thought I had targeted develop :\

**Comment by NillerMedDild** [comment]
Well now that Darkere has told me I can change target branch we can both double check :P

**Pull request merged**
