### PR TITLE
Mekanism Power Rebalancing - Ethylene is more expensive and slower to make. Fission/Fusion reduced in efficiency

### PR DESCRIPTION
**Pull request by MuteTiefling**
More info in the commits themselves. 
#861

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Excellent changes, and nice documentation/research on it. I would like to hold off on merging this until 0.4.0 though, to prevent disasters :D

**Comment by NillerMedDild** [comment]
I would like create a Wiki on this repo to document changes like this going further (this is mostly a note to self)

**Comment by MuteTiefling** [comment]
> Excellent changes, and nice documentation/research on it. I would like to hold off on merging this until 0.4.0 though, to prevent disasters :D

I thought as much. Would be pretty horrible to log in and have your reactor blow up.

**Comment by TemperedFool** [comment]
Would be a good test of player's backup systems...

**Comment by Merlo17** [comment]
Just as a kinda obvious note for us later, it might be good to mention the changed values and the wiki link in game, maybe in jei tabs or quests

**Comment by Kataiser9** [comment]
Here's my unsolicited $.02. Apologies for the long post... :'D

I disagree with the idea of nerfing fusion by two orders of magnitude in a non-expert pack, partly because _me like big numbers_ but mostly because I am not sure that it will achieve anything meaningful.  There is virtually no functional difference between 1M RF/t and 100M RF/t in a non-expert pack; even with truly outlandish factory setups you're not gonna get energy costs anywhere near that high (unless you intentionally avoid using any energy upgrades, which would make no sense considering how trivial they are to mass-produce). My SSP world with fairly extensive factory setups usually sits at 10-30k depending on use, and I doubt that most players will ever break 100k.

So this seems like a somewhat arbitrary nerf, but I realize I haven't provided much reason _not_ to nerf it. There's only one thing in this pack that uses fusion-tier energy levels, and of course that's the SPS, which is balanced around that level of energy. With the proposed 3.18M RF/t water-cooled reactor, it would take over four hours to produce a single pellet of antimatter, or about 14 hours with the air-cooled version; this doesn't really matter if you're on a server and your stuff's always running, but for SSP by kitchen sink standards that's a little nuts.

Thus, if you're set on nerfing fusion this hard, I strongly recommend revising the SPS energy costs to match.

On a less important note, is there a way to change the energy storage of the Induction Matrix? I didn't see one from a quick glance through the configs, but IMO if you nerf fusion, it would make sense to lower those values as well if possible. With the strongest power generation in the pack reduced to 1% of its normal power, it'd become quite pointless to make anything beyond a small, low-tier Induction Matrix, which would be a bit of a shame. (Of course, this isn't exactly critical since the same is _mostly_ true with default configs, but I thought I'd bring it up.)

**Comment by MuteTiefling** [comment]
> 3.18M RF/t water-cooled reactor

Do note, this is with a _very_ sub optimal setup. 

My aim in bringing basic fusion down this far was to incentivize using d-t as the booster it is meant to be. As mentioned, just a single Chemical Infuser making D-T fuel maxes out the turbine I was testing with and would end up producing a lot more energy.  5 million more rf/t in fact... and that capped out the turbine. So clearly another turbine could be useful there. 

If you're going for something as extreme as antimatter, you now have a reason to actually attempt to optimize your turbine.. As it stands, several people on the official servers have made antimatter with ethylene, and not slowly I should add. For my part, I stored all the energy from processing fissile fuel and made quite a bit of antimatter that way. 

Some changes have been implemented in Mek that will allow us to revisit this, however. My hope was to reduce the passive power gen as much as possible and force the use of the turbine for all energy. With current configs that's not possible, but the new configs will allow it. So I'll for sure be revisiting this again soon. 

If it turns out that antimatter is really out of reach with these changes, even with a better turbine than mine, then we can certainly revist the SPS.

**Comment by NillerMedDild** [comment]
@MuteTiefling Would you like this merged now, or should I wait till you've had a look at the new options? :)

**Comment by MuteTiefling** [comment]
May as well merge now. It'll make it easier to tweak when Mek finally does update

**Comment by NillerMedDild** [comment]
Documented through your dev notes here: https://github.com/NillerMedDild/Enigmatica6/wiki/Mekanism
Feel free to add/edit that as you see fit.

**Pull request merged**
