### PR TITLE
Update Valid_Apiaries

### PR DESCRIPTION
**Pull request by TemperedFool**
This adds terracotta, glazed terracotta, and concrete per #1964.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Hmm, will this capture plain Terracotta I wonder?

**Comment by TemperedFool** [comment]
It totally does when I add the appropriate commas:

image

**Comment by TemperedFool** [comment]
Scratch that, you mean undyed terracotta, which it definitely doesn't. Give me a sec...

**Comment by TemperedFool** [comment]
This time, with feeling:

image

**Pull request merged**
