### PR TITLE
Unified dies & molds

### PR DESCRIPTION
**Pull request by ochotonida**
This PR adds tags to thermal's dies and immersive engineering's molds to allow them to be used interchangeably, fixing #1722.
*However*, there's currently an issue with immersive engineering's press recipes, preventing the usage of tags as the mold. Because of this I just went ahead and unified the dies/molds, removing the packing, unpacking and gear dies from thermal.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks good! :D I'm going to un-disable the thermal ones and just hide them though, as the disabled tooltip they'd get might confuse people who already have the dies.

**Comment by NillerMedDild** [comment]
The Metal Press seems to be missing compacting recipes, and Packing 2x2, 3x3 and unpacking dies are only craftable through the Engineer's Wokrbench. Is this intended? :)

**Comment by ochotonida** [comment]
The compacting recipes from immersive engineering don't show in JEI, but they still work (I'm pretty sure it's supposed to be like that).
As for the missing recipes, I initially only had the thermal dies in the client side disabled items list. It seems that after adding them to the server side disabled items, their recipes get deleted before they get changed by the output replacement script.

**Comment by NillerMedDild** [comment]
Ah of course, you need the recipes for that, my bad!

**Pull request merged**
