### PR TITLE
Blood magic fixes

### LINKED ISSUE #823: [0.3.4] BloodMagic's Updated Book (Sanguine Sanctorum)
**Modpack version**
v0.3.4

**Issue**
The update of BloodMagic in v0.3.4 updated the book the mod uses internally (a Pachouli variant) reworked the book entirely, however, if anyone has bookmarks in the book from before the update attempting to access the bookmark crashes the client. Not sure where the Pachouli bookmarks are stored, but perhaps worth wiping those in future pack updates.

Also, a minor note, but the book appears to be blank for most entries so the quest entries that refer the player back to the book don't really go anywhere until WayOfTime gets more in there (or if the pages are intended to be filled but it's a bug they're blank?)
(e.g. This is the page for the Incense Altar)

**Logs**
The basic NPE:
```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at vazkii.patchouli.client.book.gui.GuiBookEntry.drawForegroundElements(GuiBookEntry.java:97) ~[?:1.16.4-48] {re:classloading}
	at vazkii.patchouli.client.book.gui.GuiBook.drawScreenAfterScale(GuiBook.java:134) ~[?:1.16.4-48] {re:classloading}
	at vazkii.patchouli.client.book.gui.GuiBook.func_230430_a_(GuiBook.java:122) ~[?:1.16.4-48] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.29.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1386640019.call(Unknown Source) [forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
```
Let me know if you need more of the crashlog.

### PR DESCRIPTION
**Pull request by MuteTiefling**
This gets all of our Blood Magic fixes/changes back in place in a way that doesn't break Patchouli. Fixes #823

If you're OK with where Additions Cleanup is going, I'll work on re-working the rest of the script to get it in line with the new KJS integrations. 

If you're not OK with it, we can just revert that one commit and keep the rest of the BM changes.

### CODE REVIEW

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Awesome! Thank you very much :D

> If you're OK with where Additions Cleanup is going, I'll work on re-working the rest of the script to get it in line with the new KJS integrations.
If you're not OK with it, we can just revert that one commit and keep the rest of the BM changes.

I'm OK with it, loooks better and must be faster :D

**Comment by MuteTiefling** [comment]
hrm, so I wasn't getting any errors in patchouli last night, even after multiple restarts.... but I'm getting another error today :( taking another look here

**Comment by NillerMedDild** [comment]
```
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/basic_cutting_fluid
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/basic_cutting_fluid
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/sand_iron
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/sand_gold
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/clay_from_sand
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/string
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/flint_from_gravel
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/plantoil_from_wheat
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/plantoil_from_carrots
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/plantoil_from_taters
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/plantoil_from_beets
[20:33:21] [Render thread/WARN]: Guidebook missing Alchemy Table recipe bloodmagic:alchemytable/sand_coal
```
those? :P

**Comment by MuteTiefling** [comment]
lol, yeah. Looks like I completely forgot to PR my alchemytable.js. Coming in now.

**Pull request merged**
