### PR TITLE
[Expert] RFTools update and Portality expertification

### PR DESCRIPTION
**Pull request by MuteTiefling**
Frames
image

Portal Controller:
image

Energy Module:
image

Item Module:
image

Fluid Module: 
image

Interdimensional Module:
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Environmental Controller:
image

Renamed Heat Exchanger to Entropic Gateway

**Comment by MuteTiefling** [comment]
Node:
image

Syringe:
image

Tablet:
image

**Comment by MuteTiefling** [comment]
Matter Beamer
image

Spawner: 
image

**Comment by NillerMedDild** [comment]
> would be nice to boost this but I didn't see an option in the configs

It's in the config `defaultconfigs/rftoolspower-server.toml`:

```toml
#Settings for the blazing generator
[general.blazing]
	#Amount of RF per tick the infuser uses while operating
	#Range: > 0
	blazingInfuserUsePerTick = 10
	#Amount of RF per tick the agitator uses while operating
	#Range: > 0
	blazingAgitatorUsePerTick = 10
	#Amount of RF per tick input (per side) for the infuser
	#Range: > 0
	blazingInfuserRFPerTick = 100
	#Maximum amount of power the blazing infuser can store
	#Range: > 0
	blazingInfuserMaxPower = 50000
	#Maximum amount of power the blazing generator can store
	#Range: > 0
	blazingGeneratorMaxPower = 1000000
	#Amount of RF per tick input (per side) for the agitator
	#Range: > 0
	blazingAgitatorRFPerTick = 100
	#Maximum amount of power the blazing generator give to adjacent machines per side and per tick
	#Range: > 0
	blazingGeneratorSendPerTick = 20000
	#Maximum amount of power the blazing agitator can store
	#Range: > 0
	blazingAgitatorMaxPower = 50000
```

**Comment by MuteTiefling** [comment]
> As always, very nice work :D we're getting there!

Very close, much excite!

**Pull request merged**
