### PR TITLE
[Abandoned] Tinkers Construct Questline 

### PR DESCRIPTION
**Pull request by MVethana**
Any ideas or suggestions appreciated 😃

### CODE REVIEW

**Comment by NillerMedDild** [comment]
What would you say the current status of this PR is? :)

**Comment by MVethana** [comment]
Been swamped with work and life, core quests are done just have to finish the descriptions/instructions. Adding the finishing touches on a word doc and will then transfer them to the quest. Will prob be done this sunday

**Comment by NillerMedDild** [comment]
Cool, thanks for the update!

**Comment by MVethana** [comment]
Last couple commits will be pushed and ready for review tmrw

**Comment by NillerMedDild** [comment]
Any update on this? :)

**Comment by BooBeerb** [comment]
It's been a while, MVethana? Any updates?

**Comment by mcilhargey** [comment]
I am picking this up and will be restructuring the questline a bit.

**Pull request closed without merging**
