### PR TITLE
Add Wiki button to Pack Menu

### PR DESCRIPTION
**Pull request by TemperedFool**
Shuffles the Quit and bottom row of buttons down to make room for a Wiki button. I've just copied the Github button png for it, so someone with artistic skills (which always turns out to be @Ridanisaurus it seems...) might should probably replace packmenu/resources/assets/enigmatica/textures/wiki.png.

### CODE REVIEW

**Comment by TemperedFool** [comment]
It ends up looking like this:

image

**Comment by TemperedFool** [comment]
Improved png from Rid incoming! I'll merge it after.

**Comment by TemperedFool** [comment]
Final results - @Ridanisaurus is on point with the art as usual!

image

**Comment by NillerMedDild** [comment]
Good work :D

**Pull request merged**
