### PR TITLE
Add Alex's Mobs to Torchmaster blacklists for Mega Torch and Dread Lamp

### PR DESCRIPTION
**Pull request by MuteTiefling**
Noticed on a stream last night that Centipedes keep spawning in areas protected by mega torches. Considering the problems we already had with mosquitos, I figured we should just add everything to the appropriate list.

This should do that.

### CODE REVIEW

**Comment by Mendanbar** [comment]
I haven't fully tested, but I suspect this might also be happening despite an AS Lucerna ritual on my server.  I've been running `forge entity list` in the console to keep an eye on active mobs in the world, and it seems like Alex's mobs have increased substantially in spawn count after I set up the ritual.  It's hard to say for sure, though, because I have a few loaded chunks, and the Lucerna ritual is only active in one of the regions being actively loaded.

**Comment by NillerMedDild** [comment]
Lucerna only covers hostile mobs though, right?

**Comment by TemperedFool** [comment]
I've noticed the same in my 0.3.13 world (haven't done too much in 0.4.x for realz) - those stupid centipedes are EVERYWHERE underground since Lucerna isn't blocking them.

**Comment by Mendanbar** [comment]
Yeah I thought the cave centipede was hostile.  I also have a ton of monkeys around, but figured the Lucerna ritual didn't cover those.

**Comment by Mendanbar** [comment]
I'm on the latest release (0.4.3) btw

**Comment by NillerMedDild** [comment]
Seems like an Alex's Mobs issue, based on this: https://github.com/HellFirePvP/AstralSorcery/issues/1647#issuecomment-759951409

**Pull request merged**
