### PR TITLE
[Expert] Tweaks

### PR DESCRIPTION
**Pull request by MuteTiefling**
Occultism storage has ended up a bit further back than it probably needs to be
image

Removed the botania rune, and made the tartaric gem requirement lower. Tier 2 actuators and higher still require demonic crystals

Tainted Blood Pendant moved over to Blood Altar
image

### CODE REVIEW

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Nice change imo 👍

**Comment by MuteTiefling** [comment]
Cool. Got a few more bits to put in here

**Comment by MuteTiefling** [comment]
New Wormhole base. Slightly cheaper
image

Ring of Last Chance. 
image

Amulet of Wrath
image

Removed FE cost for Scannable Scanner. Added some ore to the common ore list so they can be found without the advanced module.

Scanner
image

Module Base
image

Range
image

Living
image

Animals
image

Monsters
image

Block
image

Common Ore
image

Rare Ores
image

Fluids
image

**Comment by telemenar** [comment]
Could ammonite ore be added to the list for one of the ore categories with the scanner?

**Comment by MuteTiefling** [comment]
Hrm, good thinking. If it has an ore tag it'll be on the advanced one already, but I could move it to the common easily enough

**Comment by MuteTiefling** [comment]
Infinity Range Booster: 
image

Dimension Card
image

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
