### PR TITLE
[Expert] IF double shuffle

### PR DESCRIPTION
**Pull request by MuteTiefling**
Fluid Placer and Collector
image
Shapeless swap between modes. 

Block Placer
image

Block Breaker
image

Seed yeeter
image

Plant Gatherer:
image

Sludge Refiner
image

Latex Processing:
image

Fluid Extractor:
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
cheaper iron backpack recipe
image

**Comment by MuteTiefling** [comment]
Celestial Mycelium Filaments
image

Mycelial Reactor
image

Mycelial Generators themselves are all along the same theme, using 3 thematic items at the top and the rest being the same:
image

**Comment by MuteTiefling** [comment]
Warp Dust moved behind BM like the rest of Waystones craftables: 
image

**Comment by NillerMedDild** [comment]
Your enchanting_apparatus cleanup PR seems to be caused a conflict here :< would you mind resolving it?

**Comment by NillerMedDild** [comment]
Also the Mycelial Generators are all very expensive, did you plan to increase their generation rate? :)

**Comment by MuteTiefling** [comment]
All fixed

**Pull request merged**
