### PR TITLE
Many More Bees

### PR DESCRIPTION
**Pull request by TemperedFool**
Adds a number of new bees & the stuff to support them.

Brutish Zombee - a very large, very aggressive, very hard hitting version of the Zombee. Combs centrifuge with very good output for wax/honey, and can produce Zombie Hearts. They have the aggressive trait, so will be hostile without some sort of calming effect. Spawn at a lower rate, only at night, in the same places as the Zombee.

Cow for reference:
image

Carbee - Are Nouveau themed, crafted via Enchanting Apparatus. Combs can be used to craft Mana Honey, which has Mana Regen 3 for 8 minutes. Can also be used to craft Ars Spell Arrows for a better yield. Carbee can mutate farm animals back to their baby form (sets age to -6000), making for a possible Source farm.

image

Otherworldly Bee - Occultism-themed bee. Summoned via ritual (courtesy @MuteTiefling) sacrifice of a Rocky Bee. Can mutate bookshelves into books of binding; can also mutate andesite/oak logs into otherstone/otherworld logs. Combs can be used to craft Otherworldly Honey, which will give you a short duration & high level Ender Flu; if you can survive the resulting damage its a non-exploration method of getting some components used in Expert.

image

Shepherd Bee - It's got the meats. Combs centrifuge into mutton, wax, and honey; can mutate farm animals into adults. Combs can be used to craft various raw meat products.

image

Dusty Mummbee - Will be found in each Pharaoh's sarcophagus. Centrifuging its combs is a good source of Strange Sand; they can also be used to craft the Godforge and Godforged Blocks for less nebu/godshards.

image

Clogged/Frosty/Regal - these are all Undergarden bees; Clogged is found in the Undergarden, the other two are bred. All are good for centrifuging into the proper ore, and have mutations that produce various Undergarden materials.

image

image

image

### CODE REVIEW

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Looks good to me :D

**Comment by TemperedFool** [comment]
> Looks good to me :D
> Edit: Might wanna double check the enchanting apparatus script additions though, as Motoko made some changes to the structure earlier today.

In theory I pulled those already. I'll make sure everything merges nicely before I commit anything. Waiting for textures before I fill out the first comment some more and then update the change log.

**Comment by TemperedFool** [comment]
Carbee Crafting:
image

Crafting with comb (blocks) to increase arrow yields & craft Mana Honey:
image

Otherworldly Crafting:
image

Otherworldly Honey:
image

Atum discounts with Mummbee combs:
image

image

Meat:
image
image
image
image
image

**Comment by TemperedFool** [comment]
Getting a couple Dusty Mummbees per Pyramid:
image

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
