### PR TITLE
A couple of lang file changes to fix stones and plastics having the same name

### LINKED ISSUE #1991: Allow Using PneumaticCraft and Industrial Foregoing Plastic interchangeably
**Modpack version**
4.8.0
**Describe the bug**
Both items are called plastic, so it makes sense that you'd be able to use them interchangably.

### PR DESCRIPTION
**Pull request by pm065**
Stones:
Quark Limestone -> Ancient Limestone (may change to Lemonrock or something)
Architect's Palette Limestone -> Shrute  ¯\\\_(ツ)\_/¯
Architect's Palette Mushy Limestone -> Mycelial Shrute
Atum Limestone -> Gneiss (mods like adding limestone apparently)
Oh the Biomes You'll Go Scoria -> Rusted Scoria
Quark Marble -> Unattuned Marble (+ EE ores in case of chunk @ stonecutter usage!)

Plastic (fixes #1991)
PnematicCraft Repressurized Plastic -> ABS Pressurized Plastic as mentioned in #1991 (I kind of wanted to go over the top and call it Pneumatically Pressurized Plastic which has a nice ring to it but it looks stupid)
Industrial Foregoing Plastic -> AVS Plastic as mentioned in #1991

### CODE REVIEW

**Comment by NillerMedDild** [comment]
To be honest I don't think renaming mod items like this is a good idea. It's most likely going to cause confusion and frustration :/

**Comment by pm065** [comment]
> To be honest I don't think renaming mod items like this is a good idea. It's most likely going to cause confusion and frustration :/

Hmm, okay.

**Comment by NillerMedDild** [comment]
Sorry :/

**Comment by pm065** [comment]
> Sorry :/

No, it's fine! Don't feel guilty refusing a pull request (:

**Comment by pm065** [comment]
As always, I'll keep the branch as a backup just in case (:

**Pull request closed without merging**
