### PR TITLE
Lootboxes, Delights, Tetra Geode, IE Crate

### PR DESCRIPTION
**Pull request by Ridanisaurus**
Added:
- Loot Box and Delight Items through KubeJS:
   - Textures
   - Lang File

Updated:
- Tetra Geode Loot Table:
   - Change old Nuggets from Forge Tag to EE Items
   - Added nuggets for Lead, Nickel, Uranium, Osmium, Tin, and Zinc

- IE Crate Loot Table
   - Updated for IE Ingots and Nugget to EE Ingots and Nuggets

Removed:
- ALL Extra Disk recipes through KubeJS

### CODE REVIEW

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Good stuff, thanks!

Slightly too aggresive on the removal, but I'll fix that myself, I should've given clear instructions :P

**Comment by Ridanisaurus** [comment]
> Good stuff, thanks!
> 
> Slightly too aggresive on the removal, but I'll fix that myself, I should've given clear instructions :P

It was my understanding that all the stuff added by Extra Disks have been covered by Extra Storage, so I thought I might as well remove all recipes so nothing can be crafting from that mod to avoid any issues. Sorry about that.

**Comment by NillerMedDild** [comment]
... yeah that makes a lot of sense

**Comment by NillerMedDild** [comment]
Nah we'll have to remove Extra Storage discs and wait till 0.4.0 so people don't lose things.

**Pull request merged**
