### PR TITLE
[Expert] Mining Gadgets and other tweaks

### PR DESCRIPTION
**Pull request by MuteTiefling**
Lasers moved to Mechanical Crafting. Currently gated behind IF Ether Gas
image
Each flavor simply uses a different lens color

Upgrades:
Magnet
image

Void
image

Silk Touch
image

Freezing
image

Light Placer
image

3x3
image

Fortune 1
image

Fortune 2
image

Fortune 3
image

Range 1
image

Range 2
image

Range 3
image

Battery 1
image

Battery 2
image

Battery 3
image

Efficiency 1
image

Efficiency 2
image

Efficiency 3
image

Efficiency 4
image

Efficiency 5
image

Modification Station
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Free Runners:
image

Electric Bow
image

Configurator: 
image

Portable Teleporter
image

Charge Pad
image

Network Reader:
image

**Comment by MuteTiefling** [comment]
Brought mining laser forward a bit, updated above.

Similarly brought Ethylene/HDPE forward. 

Crusher
image

PRC
image

Gas-Burning Generator. 
image

Bio-Generator
image

Rotary Condensentrator
image


Slight change to some crafts that used the non-automatable IE circuit. Now accepts Advanced PCB which can be crafted from that same circuit, or from PNC materials. Keeps them available just as early.

Dynamic Valve
image

Solar
image

Jetpack
image

Portal Controller
image

**Comment by jlfree12** [comment]
At first this seemed really late considering I used the mining gadget all early game in normal e6 but honestly it’s nice to encourage use of like tic or tetra picks (idk how early those are I’m just assuming). Hopefully this isn’t too far behind the quarry card or digital miner tho, cause the mining gadget is a ton of fun.

**Comment by MuteTiefling** [comment]
Yeah, I've moved it up a bit from where it was. Should be late thermal to get it going.

**Comment by TemperedFool** [comment]
Looking very nice, love it!

> At first this seemed really late considering I used the mining gadget all early game in normal e6 but honestly it’s nice to encourage use of like tic or tetra picks (idk how early those are I’m just assuming). Hopefully this isn’t too far behind the quarry card or digital miner tho, cause the mining gadget is a ton of fun.

Don't you worry, both the quarry card & digital miner have been pushed back a fair amount already.

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
